#!/usr/bin/env bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

COMMAND=$1

if [ "$COMMAND" = "help" ]; then
    REAL_COMMAND=$2
    BIN="$DIR/helper/$REAL_COMMAND.sh"
    bash "$BIN" --help
    exit 0

fi

if [ "$COMMAND" = "self-update" ]; then
    cd "$DIR"
    git fetch origin --prune
    git rebase origin/master
    exit 0
fi

if [ "$COMMAND" = "get-docker-container-ip" ]; then
    BIN="$DIR/helper/get-docker-container-ip.sh"
    bash "$BIN" $2
    exit 0
fi

if [ "$COMMAND" != "" ]; then
    echo "Command [$COMMAND] was not found."
    exit 1
fi

echo "Shell Script Utilities dev-master"
echo ""
echo "Available Commands"
echo "  self-update              Upgrade utilities to the next version"
echo "  get-docker-container-ip  Display the ip of a docker container (id or name)"
echo "  help                     Display the help of a command"
