#!/usr/bin/env bash

COMMAND_NAME=$1
SOFTWARE_NAME=$2

echo "Welcome To Ubuntu Software Manager!"
echo ''

if [ $COMMAND_NAME = 'install' ]
then
    START_MESSAGE='Start Installing'
    END_MESSAGE='End Installing'
fi

if [ $COMMAND_NAME = 'update' ]
then
    START_MESSAGE='Start Updating'
    END_MESSAGE='End Updating'
fi

echo "$START_MESSAGE >>>"
echo ''

case $SOFTWARE_NAME in
    'postman')
        bash ./softwares/$SOFTWARE_NAME $COMMAND_NAME
    ;;
    'skype')
        bash ./softwares/$SOFTWARE_NAME $COMMAND_NAME
    ;;
    'vscode')
        bash ./softwares/$SOFTWARE_NAME $COMMAND_NAME
    ;;
    'source-code-pro')
        bash ./fonts/source-code-pro $COMMAND_NAME
    ;;
    'mongodb-compass')
        bash ./softwares/$SOFTWARE_NAME $COMMAND_NAME
    ;;
esac

echo ''
sudo apt-get install -f

echo ''
echo "<<< $END_MESSAGE"
